apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-api-config
  namespace: todo-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "todos"
  DB_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secrets
  namespace: todo-app
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: todo-api:v1.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: todo-api-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-api-secrets
              key: DB_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo-app
spec:
  selector:
    app: todo-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
